services:
  db-mysql:
    image: mysql:latest
    container_name: "hockey-db"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
